package-lock.json
src/services/api.js

Iniciando requisito 1. VQV!!! :rocket:

Requisito 1

---

package-lock.json
src/App.js
src/components/Index.js

…çao para pesquisa de produto e renderiza em App.js

[GRUPO 32] requisito-2. 

---

package-lock.json
src/App.js
src/components/Home.js

Criação do componente Home, com uma mensagem básica

[GRUPO 15] [REQ 2 - Cria Home] 

---

package-lock.json
src/services/api.js

Requisito 1: Fazer requisição da API do Mercado Livre.

[GRUPO-19] Requisito 1

---

package-lock.json
package.json
src/App.js
src/components/Main.js

[GRUPO 10] Requisito 2: tela principal

---

src/components/CategoriesFilter.jsx
src/pages/ListItens.jsx

Cria componente CategoriesFilter que servirá de barra lateral de filtragem por categoria de itens.

[Grupo 2] Requisito 04

---

src/Components/Home.jsx
src/Components/ProductFilter.jsx
src/Components/Products.jsx

req 05 - cria componente Product e ProductFilter e add logica+ func no componente home

[Grupo 28] requisito 05

---

src/App.js
src/components/CartButton.js
src/pages/CartPage.js
src/pages/Home.js

Adiciona Link entre Home e ShoppingCart.
Adiciona ShoppingCart page.

[Grupo 31] - Requisito 3

---

src/components/Main.css
src/components/Main.js

…pela api conforme especificado no requisito 4

[GRUPO 10] Requisito 4 - renderizado categorias na página principal

---

package-lock.json
src/App.js
src/components/Checkout.jsx
src/components/DataInput.jsx
src/components/ShoppingCart.jsx

Criado os campos de input dos dados pessoas. 
Falta:
- Checkbox com métodos de pagamento;
- listagem de produtos;
- Botão para finalizar compra;

[Group 30] requirement 12

---

src/components/productCategories/ProductCategories.js
src/components/productList/ProductList.js
src/components/search/Search.js
src/pages/home/Home.js

Refatoração da lógica dos componentes, fixando toda a lógica em apenas um local.

Main group 24 refatoracao

---

src/components/productCard/ProductCard.js
src/components/productList/ProductList.js
src/components/search/Search.js
src/pages/home/Home.js
src/services/api.js

Resolve problemas com requisito 05

[MAIN-GROUP-24][NETO-SILVA] REQUISITO 5

---

src/App.css
src/components/CategoryItem.js
src/components/CategoryList.js
src/components/ProductItem.js
src/components/ProductList.js
src/pages/Home.js
src/services/api.js

Lista de Produtos aparece na tela, mas filtro ainda não está pronto.

[Main-Group-26][Requisito-5][Requisito-6]

---

src/App.css
src/components/Categorie.js
src/pages/Home.js

Requisito 4 - Detalhes:
- Adiciona uma `<div />` com propriedade `display: flex;`  para conter duas outras `<div />`, uma ao lado esquerdo (SIDE BAR com Categorias) e outra do lado direito (SEARCH FORM com o campo de busca e descrição inicial);
- Cria uma função para fazer a requisição das categorias à API e setar o estado `categories: [],` recebendo o Array de categorias;
- Cria um `Componente` `<Categorie />` com as tags `<li />` contendo `radios` de cada categoria;
- Cria uma função para renderizar a barra lateral (SideBar) contendo o `map()` de `Componentes:` `<Categorie />` ;
- Cria uma função para manipular as categorias selecionadas e persiste a informação no `state` `selectedCategorie: ''` ;
- Renderiza a barra lateral através da função `renderSideBar()` .

[Grupo-19] Requisito 4

---

src/components/CategoriesList.js
src/pages/Home.js

Listagem de produtos por CATEGORIA implementada, handle e função de fetch na Home

[Grupo 27] Requisito 6

---

package-lock.json
src/components/ProductDetails.jsx
src/components/ProductsList.jsx

Adicionando 'Frete gratis' ao card e ao ProductDetail

[Grupo 30] Requerimento 15

---

src/App.js
src/components/ProductCard.js
src/pages/ProductDetail.js
src/services/api.js

[Grupo 31] Requisito 7 inacabado - falta passar o teste

---

src/components/CardList.js
src/components/CategoryOption.css
src/components/CategoryOption.js
src/components/HeaderMain.js
src/components/Main.js
src/components/NavMain.js

… a categoria selecionada, e criados componente NavaMain, HeaderMain e CardList para serem filhos do componente Main

[GRUPO 10] requisito 6 - Mostra items de acordo com a categoria selecionada

---

src/Components/Loading.js
src/Components/ProductCard.js
src/Components/ProductList.js
src/Components/SearchBar.js
src/Components/SearchMsg.js
src/pages/Home.js

Ainda é necessário alterar state de SearchBar para Home, porém req ok

[GRUPO 6] [REQ 5] - Gabis

---

src/pages/ProductDetails.jsx

Adiciona items ao carrinho de compras a partir dos detalhes do item

Main group 2 req 09 

---

src/App.js
src/components/ProductCard.js
src/components/ProductDetails.js
src/components/ProductList.js

Branch para o requisito 7 do projeto online store do grupo 18.

[GRUPO 18] [REQUISITO 07]

---

public/index.html
src/App.css
src/components/CategoriesList.js
src/components/Search.js
src/pages/Home.js

Adiciona um pouco de CSS para a página inicial.

[Grupo 27] Estilo CSS para página Home

---

src/App.css
src/pages/ProductsPage.jsx
src/pages/ShoppingCart.jsx

Visualiza a lista de produtos adicionados ao carrinho em sua página e permite a manipulação da sua quantidade.

[Grupo 14] - Requisito 10

---

src/components/ProductCard.js
src/pages/CartPage.js
src/pages/Home.js
src/pages/ProductDetail.js

[Grupo 31] Requisito 08

---

src/components/Infos.js

correçao bug id, onde o id nem sempre era igual, trocado para title.

[ GRUPO 32 ] Correção bug requisito 8

---

src/App.js
src/components/CartItems.jsx

Reverts tryber/sd-12-project-frontend-online-store#432

Revert "Atualização do localStorage com as alterações no carrinho"

---

src/App.js
src/components/CartItems.jsx

correção de falha em testes após merge de branches conflitantes

[Grupo 30] Resolvendo conflitos

---

src/Components/SearchList.js

Component NotFound funcionando

---

src/App.js
src/components/CategoryFilter.js
src/components/ProductDetails.js

Incluindo botão para adicionar um produto ao carrinho a partir da tela de exibição detalhada.

Group 18 req 09

---

src/App.js
src/components/Card.js
src/pages/Home.js
src/pages/ProductDetail.js
src/services/api.js

Criação da página de detalhamento do produto.

 [Grupo 19] Requisito 7

---

src/App.js
src/components/ProductsList.jsx

add comparação no map de listagens de produtos para checar se o produto está no array de cartitems

[Group 30] requirement 21 ajuste

---

src/App.js
src/__tests__/requirement10.test.js
src/components/ShoppingCart.js

adicionei o botao de - rodando sem negativar, trava no 0 só alterando o "else" do ternário.

[Grupo 23][Adiciona botoes para + e - ]

---

src/components/Checkout.jsx
src/components/ShoppingCart.jsx
src/components/subcomponents/TotalCart.jsx

Implementa componente para soma do valor total do carrinho

Valor total dos produtos

---

src/App.css
src/components/CategoriesList.js
src/components/ProductCard.js
src/components/Search.js
src/pages/Home.js

Primeira parte, pra salvar o trabalho da noite.

Adiciona Estilo a Home.

---

src/App.js
src/components/Checkout.js
src/components/Input.js
src/components/ProductList.js
src/components/ShoppingCart.js

PR para o requisito 12 do Grupo 18 do projeto online store.

[GRUPO 18] [REQUISITO 12]

---

src/Components/ProductDetail.js
src/Components/RateCard.js
src/Components/RatingArea.js

[Noobs do Github] [Requisito 11 (Finalizado)]

---

src/App.js
src/pages/ShoppingCart.js

Resolve requisito 14, impede um item seja colocado no carrinho em maior quantidade ao que possui no estoque.

[Grupo 8] Requisito 14

---

src/App.js
src/components/Main/Header/HeaderMain.js
src/components/Main/Main.js
src/components/ProductDetails/ProductDetails.js
src/components/ShoppingCart/CartItem.js
src/components/ShoppingCart/ShoppingCart.js

…nho e salvar nos itens adicionado no carrinho no local storage conforme requisitado no requisito 13

[GRUPO 10] requisito 13 - Mostrar quantidade de itens do carrinho e salva no local storage

---

src/App.css
src/components/ProductCard.js
src/components/SearchBar.js
src/pages/Cart.js
src/pages/Home.js

Adiciona um `<button>` para capturar o produto selecionado na `Home.js` Página Principal e caso o usuário acesse o carrinho, deverá ser exibido o título e quantidade de cada produto.

[Grupo 19] Requisito 8

---

src/App.css
src/App.js
src/components/Checkout.jsx
src/components/CompletePurchase.jsx
src/components/Header.jsx
src/components/ProductDetails.jsx
src/components/ShoppingCart.jsx

modifica header para ser dinâmico dependendo da página

[Grupo 30] Header dinâmico

---

src/components/ProductCard.js
src/components/ShoppingCard.js
src/pages/Details.js
src/pages/Main.js

Adiciona total de produtos na main, página de detalhes e página do carrinho

[main-group-5] Requisito 13

---

src/App.js
src/components/Checkout.css
src/components/Checkout.js
src/components/Input.js

COmplementacao do requisito 12 para o Grupo 18 do Projeto online store.

[GRUPO 18] [REQUISITO 12-2]

---

src/components/subcomponents/CartSlider.jsx

adiciona o valor total no slider

[Group 30] cart slider total

---

src/App.js
src/components/ShoppingCart/CartItem.js

[GRUPO 10] Refatoração de logica de quantidade

---

src/Components/ProductList.js
src/Components/SearchBar.js
src/pages/Home.js
src/pages/ProductDetails.js
src/pages/ShoppingCart.js

ATENÇÃO!!
Requisito 8 está ok. Requisito 5 quebrando devido à linha 8 do componente SearchBar, ao comentar essa linha o requisito 5 passa, porém o requisito 2 quebra. =/

[Grupo 6] Requisito 8

---

src/Components/ProductList.js
src/pages/ProductDetails.js

Coloquei o botão de adicionar ao carrinho na página de detalhes de um produto. Porém não consegui passar a função addToShoppingCart para o botão ou a página ProductDetails.js.

[GRUPO 6] Inicia requisito 9

---

src/App.css
src/Components/ButtonCart.js
src/Components/ProductList.js
src/Components/SearchBar.js
src/pages/Home.js

Adiciona CSS à lista de produtos

[GRUPO 6] CSS

---

src/App.js
src/components/BtnCart.css
src/components/Checkout.css
src/components/Checkout.js
src/components/FastCheckout.js
src/components/ProductList.css
src/components/ProductList.js
src/components/ShoppingCart.js
src/services/data.js

Bug fixes para o projeto do grupo 18.

[GRUPO 18] [BUG-FIXES]

---

src/App.js
src/components/BtnCart.css
src/components/Checkout.css
src/components/Checkout.js
src/components/ProductList.css
src/components/ProductList.js
src/services/data.js

PR para o Requisito 18 do grupo 18.

[GRUPO 18] [REQUISITO 18]

---

src/App.css
src/App.js
src/pages/Cart.js
src/pages/Checkout.js

[GRUPO 19] Requisito 12

---

src/components/DetailsHeader.js
src/components/SearchBar.js
src/pages/ProductDetails.js

Adiciona um campo com a tag `<span />` para receber a quantidade de produtos no carrinho na páginas **Home** e **ProductDetails**.

[GRUPO 19] Requisito 13

---

src/App.css
src/components/ProductCard.js

Mostra quais produtos possuem frete grátis em uma _tag_ `<span />` renderizada no componente `<ProductCard />` dentro da página **Home**.

[GRUPO 19] Requisito 15
